version: '3.4'

services:
  db:
    image: restful-api-joaodias-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: restful-api-joaodias
    ports:
     - 3308:3306
    networks:
     - restful-api-joaodias-network

  restful-api-joaodias:
    image: restful-api-joaodias
    build:
      context: .
      dockerfile: restful-api-joaodias/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Development
    ports:
     - 7093:80
    depends_on:
     - db
    networks:
     - restful-api-joaodias-network
networks:
  restful-api-joaodias-network:
    driver: bridge

